# Generated by Django 5.2.15 on 2026-06-12 06:35

import core.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('surface', models.CharField(choices=[('SINTETICO', 'Sintetico'), ('GRASS', 'Grass'), ('PARQUET', 'Parquet'), ('CEMENTO', 'Cemento'), ('ARCILLA', 'Arcilla'), ('CRISTAL', 'Cristal'), ('OTRO', 'Otro')], max_length=30)),
                ('covered', models.BooleanField(default=False)),
                ('lighting', models.BooleanField(default=False)),
                ('standard_rate', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cancha',
                'ordering': ['complex__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('OPERATIVO', 'Operativo'), ('DANADO', 'Danado')], default='OPERATIVO', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'extra',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'deporte',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('JUGADOR', 'Jugador'), ('ADMINISTRADOR', 'Administrador'), ('SOPORTE', 'Soporte')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'cuenta',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', core.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tax_id', models.CharField(max_length=11, unique=True)),
                ('business_name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='administrator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'administrador',
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('ABIERTA', 'Abierta'), ('EN_PROCESO', 'En proceso'), ('RESUELTA', 'Resuelta')], default='ABIERTA', max_length=20)),
                ('severity', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], max_length=10)),
                ('resolution_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'incidencia',
                'ordering': ['status', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('ranking_points', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jugador',
            },
        ),
        migrations.CreateModel(
            name='Hold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('starts_at', models.TimeField()),
                ('ends_at', models.TimeField()),
                ('status', models.CharField(choices=[('ACTIVO', 'Activo'), ('EXPIRADO', 'Expirado'), ('CONVERTIDO', 'Convertido'), ('CANCELADO', 'Cancelado')], default='ACTIVO', max_length=20)),
                ('court_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=core.models.default_hold_expiry)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holds', to='core.court')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holds', to='core.playerprofile')),
            ],
            options={
                'db_table': 'bloqueo_horario',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('weekday', models.PositiveSmallIntegerField()),
                ('starts_at', models.TimeField()),
                ('ends_at', models.TimeField()),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('active', models.BooleanField(default=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_rules', to='core.court')),
            ],
            options={
                'db_table': 'regla_precio',
                'ordering': ['court', 'weekday', 'starts_at'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(editable=False, max_length=20, unique=True)),
                ('scheduled_date', models.DateField()),
                ('starts_at', models.TimeField()),
                ('ends_at', models.TimeField()),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('VENCIDA', 'Vencida')], default='PENDIENTE', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('refund_eligible', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='core.court')),
                ('hold', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reservation', to='core.hold')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='core.playerprofile')),
            ],
            options={
                'db_table': 'ticket_reserva',
                'ordering': ['-scheduled_date', '-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia'), ('BILLETERA_DIGITAL', 'Billetera digital'), ('VALIDACION_MANUAL', 'Validacion manual')], max_length=30)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('FALLIDO', 'Fallido'), ('REEMBOLSADO', 'Reembolsado')], default='PENDIENTE', max_length=20)),
                ('proof', models.ImageField(blank=True, upload_to='payment_proofs/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('rejection_reason', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='core.reservation')),
            ],
            options={
                'db_table': 'pago',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReservationExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.extra')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_extras', to='core.reservation')),
            ],
            options={
                'db_table': 'reserva_extra',
            },
        ),
        migrations.AddField(
            model_name='court',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courts', to='core.sport'),
        ),
        migrations.CreateModel(
            name='SportsComplex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('administrator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complexes', to='core.adminprofile')),
            ],
            options={
                'db_table': 'complejo_deportivo',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OpeningSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField()),
                ('enabled', models.BooleanField(default=True)),
                ('opens_at', models.TimeField(default='08:00')),
                ('closes_at', models.TimeField(default='22:00')),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.sportscomplex')),
            ],
            options={
                'db_table': 'horario_complejo',
            },
        ),
        migrations.AddField(
            model_name='extra',
            name='complex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='core.sportscomplex'),
        ),
        migrations.AddField(
            model_name='court',
            name='complex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courts', to='core.sportscomplex'),
        ),
        migrations.CreateModel(
            name='HoldExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.extra')),
                ('hold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_extras', to='core.hold')),
            ],
            options={
                'db_table': 'bloqueo_extra',
                'constraints': [models.UniqueConstraint(fields=('hold', 'extra'), name='uq_hold_extra')],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceClosure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('starts_at', models.TimeField()),
                ('ends_at', models.TimeField()),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_closures', to='core.court')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cierre_cancha',
                'indexes': [models.Index(fields=['court', 'date'], name='cierre_canc_court_i_04aeb4_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='ck_closure_hours')],
            },
        ),
        migrations.AddIndex(
            model_name='hold',
            index=models.Index(fields=['court', 'date', 'starts_at', 'ends_at'], name='bloqueo_hor_court_i_830c3c_idx'),
        ),
        migrations.AddIndex(
            model_name='hold',
            index=models.Index(fields=['player', 'status'], name='bloqueo_hor_player__ada675_idx'),
        ),
        migrations.AddConstraint(
            model_name='hold',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='ck_hold_hours'),
        ),
        migrations.AddConstraint(
            model_name='hold',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('created_at'))), name='ck_hold_expiry'),
        ),
        migrations.AddIndex(
            model_name='pricerule',
            index=models.Index(fields=['court', 'weekday'], name='regla_preci_court_i_6bdb8f_idx'),
        ),
        migrations.AddConstraint(
            model_name='pricerule',
            constraint=models.UniqueConstraint(fields=('court', 'weekday', 'starts_at', 'ends_at'), name='uq_price_rule_range'),
        ),
        migrations.AddConstraint(
            model_name='pricerule',
            constraint=models.CheckConstraint(condition=models.Q(('weekday__gte', 1), ('weekday__lte', 7)), name='ck_price_rule_weekday'),
        ),
        migrations.AddConstraint(
            model_name='pricerule',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='ck_price_rule_hours'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['court', 'scheduled_date'], name='ticket_rese_court_i_67ec2c_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['player', 'scheduled_date'], name='ticket_rese_player__7f6c8f_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['status'], name='ticket_rese_status_77ffba_idx'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='ck_reservation_hours'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('total_price__gte', 0)), name='ck_reservation_total'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='pago_status_8932ae_idx'),
        ),
        migrations.AddConstraint(
            model_name='reservationextra',
            constraint=models.UniqueConstraint(fields=('reservation', 'extra'), name='uq_reservation_extra'),
        ),
        migrations.AddConstraint(
            model_name='openingschedule',
            constraint=models.UniqueConstraint(fields=('complex', 'weekday'), name='uq_schedule_complex_day'),
        ),
        migrations.AddConstraint(
            model_name='openingschedule',
            constraint=models.CheckConstraint(condition=models.Q(('weekday__gte', 1), ('weekday__lte', 7)), name='ck_schedule_weekday'),
        ),
        migrations.AddConstraint(
            model_name='openingschedule',
            constraint=models.CheckConstraint(condition=models.Q(('closes_at__gt', models.F('opens_at'))), name='ck_schedule_hours'),
        ),
        migrations.AddConstraint(
            model_name='extra',
            constraint=models.UniqueConstraint(fields=('complex', 'name'), name='uq_extra_name_per_complex'),
        ),
        migrations.AddIndex(
            model_name='court',
            index=models.Index(fields=['complex', 'sport'], name='cancha_complex_71a013_idx'),
        ),
        migrations.AddConstraint(
            model_name='court',
            constraint=models.UniqueConstraint(fields=('complex', 'name'), name='uq_court_name_per_complex'),
        ),
    ]
